### ISSUE TITLE
close result pop-up using escape key

### ISSUE THREAD

**Issue by amitoj-singh** [amitoj-singh/timeSpan#12]
We want to close this output popup using `esc` key.
After clicking submit if the user clicks `esc` on keyboard the popup should vanish, similar to the way when cross (X) icon is clicked.

**Please go through these [guidelines](https://github.com/amitoj-singh/timeSpan/blob/master/Contributing.md) if you consider helping in this issue.**

![image](https://user-images.githubusercontent.com/31106921/95357138-2074f180-08e5-11eb-9ad6-9cb9ef1a415e.png)

**Comment by Leos1113** [comment]
Can you assign me this issue?

**Comment by amitoj-singh** [comment]
> Can you assign me this issue?

Sure👍

**Comment by amitoj-singh** [comment]
Hey @Leos1113 would you like to discuss anything if you are working on it?

**Comment by Leos1113** [comment]
I'm working on it! Sorry for the delay

**Comment by Leos1113** [comment]
https://github.com/amitoj-singh/timeSpan/pull/13 done!
