### ISSUE TITLE
Prefill default values of date and time as per (Indian Standard Time)

### ISSUE THREAD

**Issue by amitoj-singh** [amitoj-singh/timeSpan#5]
Set default values of form fields to the current time when the document is opened in (IST).

![image](https://user-images.githubusercontent.com/31106921/95221931-96118c80-0815-11eb-841f-66cc1789ecbe.png)

**Comment by VectorXz** [comment]
I would like to work on this!

**Comment by rahuldhangar** [comment]
I have made changes and sending a pull request. Please check and see if it works for you!

**Comment by VectorXz** [comment]
I've raise PR at #6  , please check it out and consider merging it or add label "hacktoberfest-accepted" if they're ok. Thank you!

**Comment by rahuldhangar** [comment]
This issue (along with the other open bug) has been resolved in my PR at #11 through two separate commits, one for each task.
Kindly consider merging it or add label "hacktoberfest-accepted" if they're ok. Thanks!

**Comment by amitoj-singh** [comment]
I need some help.
I want both @rahuldhangar and @VectorXz contribution be accredited. Do I need to merge both PRs?
Or like how did it work when we have two PRs for same issue?
What should I do? 👀

**Comment by VectorXz** [comment]
Thank you, actually I'm just a beginner to Github this Hacktoberfest 2020. I also don't know how to deal with 2 PR on same issues, but I think it is up to you, which code seems to be fits you the best, just merge that one and left the other one as it is. I think hacktoberfest-accepted is fine for us although it not get merge. Thank you for your kindness! 👍

**Comment by amitoj-singh** [comment]
> Thank you, actually I'm just a beginner to Github this Hacktoberfest 2020. I also don't know how to deal with 2 PR on same issues, but I think it is up to you, which code seems to be fits you the best, just merge that one and left the other one as it is. I think hacktoberfest-accepted is fine for us although it not get merge. Thank you for your kindness! 👍

So, just adding the label `hacktoberfest-accepted` counts a pull request in Hacktoberfest dashboard.
That's cool.

Thank you
