### ISSUE TITLE
Default value for fields that empty to be current date/time

### ISSUE THREAD

**Issue by VectorXz** [amitoj-singh/timeSpan#8]
If input time for adding is empty, it will show NaN result.

![Screenshot_10](https://user-images.githubusercontent.com/9075013/95225897-8484b080-0826-11eb-9424-3f9d87499fb1.png)

**Comment by VectorXz** [comment]
Please assign this issue to me, I want to solve this. Thank you!

**Comment by VectorXz** [comment]
I've raise PR at #9 , please check it out and consider merging it or add label "hacktoberfest-accepted" if they're ok. Thank you!

**Comment by rahuldhangar** [comment]
This bug (along with the other open issue) has been resolved in my PR at #11 
Request you to consider merging it or add label "hacktoberfest-accepted" if they're ok. Thanks!
